### PR TITLE
patterns: add threeDeeBlink and shadesOutlineChase

### PR DESCRIPTION
**Pull request by mplewis**
threeDeeBlink: Just like threeDee, except it flip flops red/blue back and forth quickly.

shadesOutlineChase: Just like shadesOutline, except the trail has a fixed length. When the trail gets too long, it goes dark at the tail, giving it a "Snake"-like effect.

### CODE REVIEW

**Comment by doublejosh** [comment]
Picture or video?

**Comment by mplewis** [comment]
Sure! I can get one when I am near my glasses.

**Comment by mplewis** [comment]
Links to videos for each effect:

* [threeDeeBlink](http://gfycat.com/NarrowBabyishIndianpangolin)
* [shadesOutlineChase](http://gfycat.com/DecimalJointIriomotecat)

**Comment by tekromancr** [comment]
Very cool stuff! The snake is REALLY cool. I might peek at that for a snake-game effect I am working on.

I am a tad worried about possible legal encounters with the "Cherries & Berries"-like effect of the blinking threeDee, though. Honestly, it shouldn't ever be a problem, but stranger things have happened.

**Comment by mplewis** [comment]
Haha, that is fair. I will make sure not to use it on the motorcycle...

**Pull request closed without merging**
